import * as core from '@actions/core';
import * as github from '@actions/github';
import * as exec from '@actions/exec';
import { ActionConfig, GeneratedTest } from '../types';

// [FIX #2] Sanitize strings for use in commit messages
function sanitizeForCommitMessage(value: string): string {
  // Remove control characters and backticks that could affect git hooks or parsers
  // eslint-disable-next-line no-control-regex
  return value.replace(/[`\x00-\x1f\x7f]/g, '');
}

export class GitOps {
  private octokit: ReturnType<typeof github.getOctokit>;

  constructor() {
    const token = process.env.GITHUB_TOKEN;
    if (!token) throw new Error('GITHUB_TOKEN is required for git operations');
    this.octokit = github.getOctokit(token);
  }

  async commitTests(tests: GeneratedTest[], headSha: string, fixtureFiles: string[] = []): Promise<void> {
    await this.execGit('config', 'user.name', 'autospec-ai[bot]');
    await this.execGit('config', 'user.email', 'autospec-ai[bot]@users.noreply.github.com');

    for (const test of tests) {
      await this.execGit('add', test.filepath);
    }
    for (const fixture of fixtureFiles) {
      await this.execGit('add', fixture);
    }

    // [FIX #2] Sanitize filenames and SHA in commit message
    const fileList = sanitizeForCommitMessage(tests.map(t => t.filename).join(', '));
    const shortSha = sanitizeForCommitMessage(headSha.slice(0, 8));
    await this.execGit(
      'commit',
      '-m',
      `test(autospec): generate E2E tests\n\nFiles: ${fileList}\nTriggered by: ${shortSha}`
    );

    await this.execGit('push');
    core.info('Committed and pushed generated tests');
  }

  async createPR(tests: GeneratedTest[], baseBranch: string, headSha: string, config?: ActionConfig, fixtureFiles: string[] = []): Promise<number> {
    const context = github.context;
    const shortSha = sanitizeForCommitMessage(headSha.slice(0, 8));
    const branchName = `autospec/tests-${shortSha}`;

    // Create and push branch
    await this.execGit('config', 'user.name', 'autospec-ai[bot]');
    await this.execGit('config', 'user.email', 'autospec-ai[bot]@users.noreply.github.com');
    await this.execGit('checkout', '-b', branchName);

    for (const test of tests) {
      await this.execGit('add', test.filepath);
    }
    for (const fixture of fixtureFiles) {
      await this.execGit('add', fixture);
    }

    const fileList = sanitizeForCommitMessage(tests.map(t => t.filename).join(', '));
    await this.execGit(
      'commit',
      '-m',
      `test(autospec): generate E2E tests\n\nFiles: ${fileList}`
    );
    await this.execGit('push', '--set-upstream', 'origin', branchName);

    // Build PR body
    const body = this.buildPRBody(tests, headSha, config, fixtureFiles);

    // Create PR
    const { data: pr } = await this.octokit.rest.pulls.create({
      owner: context.repo.owner,
      repo: context.repo.repo,
      title: `🤖 AutoSpec: Generated ${tests.length} E2E test${tests.length > 1 ? 's' : ''}`,
      body,
      head: branchName,
      base: baseBranch,
    });

    // Add label
    try {
      await this.octokit.rest.issues.addLabels({
        owner: context.repo.owner,
        repo: context.repo.repo,
        issue_number: pr.number,
        labels: ['autospec', 'e2e-tests', 'ai-generated'],
      });
    } catch {
      // Labels might not exist, that's fine
    }

    core.info(`Created PR #${pr.number}: ${pr.html_url}`);
    return pr.number;
  }

  private buildPRBody(tests: GeneratedTest[], headSha: string, config?: ActionConfig, fixtureFiles: string[] = []): string {
    const shortSha = sanitizeForCommitMessage(headSha.slice(0, 8));
    const testList = tests
      .map(t => `- \`${sanitizeForCommitMessage(t.filepath)}\` — ${sanitizeForCommitMessage(t.description)}`)
      .join('\n');

    let body = `## 🤖 AutoSpec AI - Generated E2E Tests

This PR was automatically generated by [AutoSpec AI](https://github.com/autospec-ai/action) based on code changes in \`${shortSha}\`.

### Generated Tests
${testList}

### What to Review
- [ ] Test assertions are meaningful and correct
- [ ] Selectors are stable (prefer data-testid or accessible selectors)
- [ ] No flaky patterns (hardcoded waits, race conditions)
- [ ] Tests cover the intended user flows

### Source Files
${tests.flatMap(t => t.sourceFiles).map(f => `- \`${sanitizeForCommitMessage(f)}\``).join('\n')}`;

    // Feature-specific PR sections
    if (config?.traceOnFailure) {
      body += `

### 🔍 Trace Viewer
Tests are configured with \`trace: '${config.traceMode}'\`. After running tests, view traces with:
\`\`\`bash
npx playwright show-trace test-results/<test-name>/trace.zip
\`\`\``;
    }

    if (fixtureFiles.length > 0) {
      const fixtureList = fixtureFiles.map(f => `- \`${sanitizeForCommitMessage(f)}\``).join('\n');
      body += `

### 📦 Extracted Fixtures
API mocks were extracted into shared fixture files:
${fixtureList}`;
    }

    if (config?.visualRegression) {
      body += `

### 📸 Visual Regression Baselines
Tests include \`toHaveScreenshot()\` assertions. On first run, Playwright will generate baseline screenshots. Update baselines with:
\`\`\`bash
npx playwright test --update-snapshots
\`\`\``;
    }

    if (config?.accessibilityAssertions || config?.axeScan) {
      body += `

### ♿ Accessibility
${config?.accessibilityAssertions ? '- Aria snapshot assertions validate the accessibility tree structure.\n' : ''}${config?.axeScan ? `- Axe-core scans check against \`${config.axeStandard}\` standard.\n` : ''}`;
    }

    body += `

---
<sub>Generated by AutoSpec AI • [Report Issue](https://github.com/autospec-ai/action/issues)</sub>`;

    return body;
  }

  // Note: Uses @actions/exec which passes args as an array (safe from shell injection)
  private async execGit(...args: string[]): Promise<string> {
    let output = '';
    await exec.exec('git', args, {
      listeners: {
        stdout: (data: Buffer) => { output += data.toString(); },
      },
      silent: true,
    });
    return output.trim();
  }
}
